import {Colors} from '@/constants/colors';
import {Fonts} from '@/constants/fonts';
import {theme} from '@/constants/theme';
import {moderateScale, moderateScaleVertical} from '@/utils/responsiveSize';
import {StyleSheet} from 'react-native';

export const serviceUi = StyleSheet.create({
  card: {
    backgroundColor: Colors.white,
    borderRadius: moderateScale(20),
    padding: moderateScale(20),
    marginBottom: moderateScaleVertical(14),
    borderWidth: 1,
    borderColor: Colors.line,
    ...theme.shadow,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: moderateScale(12),
    marginBottom: moderateScaleVertical(14),
  },
  refreshBtn: {
    paddingVertical: moderateScaleVertical(11),
    paddingHorizontal: moderateScale(16),
    borderRadius: moderateScale(14),
    borderWidth: 1.5,
    borderColor: Colors.line,
    backgroundColor: Colors.white,
  },
  refreshBtnText: {
    color: Colors.black,
    fontFamily: Fonts.inter.bold,
    fontSize: moderateScale(13),
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: moderateScale(14),
    borderWidth: 1.5,
    borderColor: Colors.line,
    paddingHorizontal: moderateScale(14),
    minHeight: moderateScaleVertical(50),
    marginBottom: moderateScaleVertical(12),
    ...theme.shadow,
    shadowOpacity: 0.06,
    elevation: 2,
  },
  searchRowFocused: {
    borderColor: Colors.brand,
    backgroundColor: Colors.white,
  },
  searchInput: {
    flex: 1,
    fontSize: moderateScale(14),
    color: Colors.black,
    paddingVertical: moderateScaleVertical(12),
    fontFamily: Fonts.inter.regular,
  },
  serviceList: {
    gap: moderateScaleVertical(10),
  },
  serviceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(14),
    padding: moderateScale(16),
    borderWidth: 1.5,
    borderColor: Colors.line,
    borderRadius: moderateScale(14),
    backgroundColor: Colors.white,
    ...theme.shadow,
    shadowOpacity: 0.06,
    elevation: 2,
  },
  serviceCardPressed: {
    borderColor: Colors.brand,
    backgroundColor: Colors.brandSoft,
  },
  serviceAvatar: {
    width: moderateScale(50),
    height: moderateScale(50),
    borderRadius: moderateScale(14),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 3,
  },
  serviceChevron: {
    width: moderateScale(36),
    height: moderateScale(36),
    borderRadius: 18,
    backgroundColor: Colors.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  serviceMeta: {
    color: Colors.muted,
    marginTop: 2,
    fontSize: moderateScale(12),
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: moderateScaleVertical(12),
    paddingVertical: moderateScaleVertical(8),
  },
  backBtnText: {
    color: Colors.brandDark,
    fontFamily: Fonts.inter.bold,
    fontSize: moderateScale(14),
  },
  selectedBanner: {
    paddingVertical: moderateScaleVertical(14),
    paddingHorizontal: moderateScale(16),
    borderRadius: moderateScale(14),
    backgroundColor: Colors.brandSoft,
    borderWidth: 1,
    borderColor: 'rgba(4, 120, 87, 0.15)',
    marginBottom: moderateScaleVertical(14),
  },
  selectedBannerLabel: {
    color: Colors.black,
    fontSize: moderateScale(14),
  },
  selectedBannerName: {
    color: Colors.brandDark,
    fontFamily: Fonts.inter.bold,
  },
  field: {
    marginBottom: moderateScaleVertical(16),
  },
  fieldLabel: {
    color: Colors.black,
    fontFamily: Fonts.inter.bold,
    fontSize: moderateScale(12),
    letterSpacing: 0.3,
    marginBottom: moderateScaleVertical(7),
    textTransform: 'uppercase',
  },
  formInput: {
    backgroundColor: Colors.bg,
    borderRadius: moderateScale(14),
    borderWidth: 1.5,
    borderColor: Colors.line,
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScaleVertical(14),
    fontSize: moderateScale(14),
    color: Colors.black,
    fontFamily: Fonts.inter.regular,
  },
  formInputFocused: {
    borderColor: Colors.brand,
    backgroundColor: Colors.white,
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  checkboxGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: moderateScale(8),
  },
  checkboxPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: moderateScale(6),
    paddingVertical: moderateScaleVertical(10),
    paddingHorizontal: moderateScale(14),
    borderRadius: moderateScale(14),
    borderWidth: 1.5,
    borderColor: Colors.line,
    backgroundColor: Colors.white,
    minWidth: moderateScale(100),
  },
  checkboxPillHalf: {
    flex: 1,
    minWidth: '45%',
  },
  checkboxPillChecked: {
    borderColor: Colors.brand,
    backgroundColor: Colors.brandSoft,
  },
  checkboxPillText: {
    fontSize: moderateScale(13),
    color: Colors.black,
    fontFamily: Fonts.inter.semiBold,
  },
  checkboxPillTextChecked: {
    color: Colors.brandDark,
  },
  submitBtn: {
    borderRadius: moderateScale(14),
    overflow: 'hidden',
    marginTop: moderateScaleVertical(8),
    shadowColor: Colors.brand,
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 5,
  },
  submitBtnInner: {
    paddingVertical: moderateScaleVertical(15),
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitBtnText: {
    color: Colors.white,
    fontFamily: Fonts.inter.bold,
    fontSize: moderateScale(15),
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: moderateScale(20),
    borderTopRightRadius: moderateScale(20),
    paddingBottom: moderateScaleVertical(24),
    maxHeight: '60%',
  },
  modalOption: {
    paddingVertical: moderateScaleVertical(16),
    paddingHorizontal: moderateScale(20),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.line,
  },
});
